#!/bin/sh
status=$(cat /sys/class/power_supply/BAT0/status)
percent=$(cat /sys/class/power_supply/BAT0/capacity)

if [ "$status" = "Charging" ]; then
	icon="󰂄"
elif [ "$percent" -gt 95 ]; then
	icon="󰁹"
elif [ "$percent" -gt 85 ]; then
	icon="󰂂"
elif [ "$percent" -gt 75 ]; then
	icon="󰂁"
elif [ "$percent" -gt 65 ]; then
	icon="󰂀"
elif [ "$percent" -gt 55 ]; then
	icon="󰁿"
elif [ "$percent" -gt 45 ]; then
	icon="󰁾"
elif [ "$percent" -gt 35 ]; then
	icon="󰁽"
elif [ "$percent" -gt 25 ]; then
	icon="󰁼"
elif [ "$percent" -gt 15 ]; then
	icon="󰁻"
elif [ "$percent" -gt 5 ]; then
	icon="󰁺"
else
	icon="󰂃"
fi
echo "$icon"
