[helpers]

# Shell etc

[git.files]
"git/.gitignore" = "~/.gitignore"
"git/config" = "$XDG_CONFIG_HOME/git/config"
"git/commit-template.txt" = "$XDG_CONFIG_HOME/git/commit-template.txt"

[zsh.files]
"zsh/.zshenv" = "~/.zshenv"
"zsh" = { target = "$XDG_CONFIG_HOME/zsh", type = "symbolic" }

[tmux.files]
"tmux/tmux.conf" = "$XDG_CONFIG_HOME/tmux/tmux.conf"

[nvim.files]
"nvim" = "$XDG_CONFIG_HOME/nvim"


# Terms

[alacritty.files]
"terms/alacritty" = "$XDG_CONFIG_HOME/alacritty"

[kitty.files]
"terms/kitty" = "$XDG_CONFIG_HOME/kitty"

[wezterm.files]
"terms/wezterm" = "$XDG_CONFIG_HOME/wezterm"


# GUI

[X.files]
"X11/xinitrc" = "$XDG_CONFIG_HOME/X11/xinitrc"
"X11/xresources" = "$XDG_CONFIG_HOME/X11/Xresources"

[awesome.files]
"awesome" = { target = "$XDG_CONFIG_HOME/awesome", type = "symbolic" }

[hyprland.files]
"hypr" = { target = "$XDG_CONFIG_HOME/hypr", type = "symbolic" }

[eww.files]
"eww" = { target = "$XDG_CONFIG_HOME/eww", type = "symbolic" }

[waybar.files]
"waybar" = { target = "$XDG_CONFIG_HOME/waybar", type = "symbolic" }

# Misc

[bottom.files]
"bottom" = { target = "$XDG_CONFIG_HOME/bottom", type = "symbolic" }

[flameshot.files]
"flameshot" = { target = "$XDG_CONFIG_HOME/flameshot", type = "symbolic" }

[gtk3.files]
"gtk3" = { target = "$XDG_CONFIG_HOME/gtk-3.0", type = "symbolic" }

[lazygit.files]
"lazygit" = { target = "$XDG_CONFIG_HOME/lazygit", type = "symbolic" }

[neofetch.files]
"neofetch" = { target = "$XDG_CONFIG_HOME/neofetch", type = "symbolic" }

[picom.files]
"picom" = "$XDG_CONFIG_HOME/picom"

[rofi.files]
"rofi/rofimoji.rc" = "$XDG_CONFIG_HOME/rofimoji.rc"
# "rofi/.emoji_list" = ".emoji_list"
"rofi" = "$XDG_CONFIG_HOME/rofi"

[wofi.files]
"wofi" = { target = "$XDG_CONFIG_HOME/wofi", type = "symbolic" }

[dunst.files]
"dunst" = { target = "$XDG_CONFIG_HOME/dunst", type = "symbolic" }

[swaync.files]
"swaync" = { target = "$XDG_CONFIG_HOME/swaync", type = "symbolic" }


# Packs

[linux-shell]
depends = ["git", "zsh", "tmux", "bottom", "lazygit", "neofetch"]

[linux-gui]
depends = [
  "linux-shell",
  "X",
  "gtk3",
  "picom",
  "wezterm",
  "awesome",
  "rofi",
  "wofi",
  "dunst",
  "hyprland",
  "eww",
  "waybar",
  "swaync",
  "flameshot",
]
